apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vscode-java
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/computate-org/vscode-java"
    opendatahub.io/notebook-image-name: "VSCode IJava java-17-openjdk"
    opendatahub.io/notebook-image-desc: |-
      An OpenShift AI Image for Java development. 
      Based on IJava project by SpencerPark on GitHub for Jupyter Lab Notebook integration. 
      Uses java-17-openjdk-devel and maven package support.
      Used by the Smarta Byar Smart Village Community using AI/ML code generation technology for Smart Data Model APIs. 
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'ghcr.io/nerc-images/vscode-java:main'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source

